version: "3"

services:

  builder:
    container_name: builder
    build:
      context: ./
      dockerfile: builder/Dockerfile
    volumes:
      - ./builder:/source
      - ./shared:/shared
  
  data_generation:
    container_name: data_generation
    profiles: [ "data_generation" ]
    build:
      context: ./
      dockerfile: data_generation/Dockerfile
    volumes:
      - ./data_generation:/source
      - ./shared:/shared
      - ${INDEX_PATH}:/index
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    depends_on:
      - builder
  
  model_training:
    container_name: model_training
    profiles: [ "model_training" ]
    build:
      context: ./
      dockerfile: model_training/Dockerfile
    volumes:
      - ./model_training:/source
      - ./shared:/shared
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0', '1', '3', '7']
              capabilities: [gpu]
    depends_on:
      - builder
    
  user_simulator:
    container_name: user_simulator
    build:
      context: ./
      dockerfile: USi/Dockerfile
    volumes:
      - ./USi:/source
      - ./shared:/shared
      - ${INDEX_PATH}:/index
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1', '2']
              capabilities: [gpu]
    depends_on:
      - builder
    