version: "3"

services:

  builder:
    container_name: builder
    build:
      context: ./
      dockerfile: builder/Dockerfile
    volumes:
      - ./builder:/source
      - ./shared:/shared
  
  data_generation:
    container_name: data_generation
    build:
      context: ./
      dockerfile: data_generation/Dockerfile
    volumes:
      - ./data_generation:/source
      - ./shared:/shared
      - ${INDEX_PATH}:/index
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    depends_on:
      - builder